abbr -a gb 'git branch'
abbr -a gba 'git branch -a'
abbr -a gbd 'git branch -d'
abbr -a gbD 'git branch -D'
abbr -a gbl 'git blame -b -w'
abbr -a gbnm 'git branch --no-merged'
abbr -a gbr 'git branch --remote'
abbr -a gbs 'git bisect'
abbr -a gbsb 'git bisect bad'
abbr -a gbsg 'git bisect good'
abbr -a gbsr 'git bisect reset'
abbr -a gbss 'git bisect start'
abbr -a gc 'git commit -v'
abbr -a gc! 'git commit -v --amend'
abbr -a gcn! 'git commit -v --no-edit --amend'
abbr -a gca 'git commit -v -a'
abbr -a gca! 'git commit -v -a --amend'
abbr -a gcan! 'git commit -v -a --no-edit --amend'
abbr -a gcans! 'git commit -v -a -s --no-edit --amend'
abbr -a gcam 'git commit -a -m'
abbr -a gcsm 'git commit -s -m'
abbr -a gcb 'git checkout -b'
abbr -a gcf 'git config --list'
abbr -a gcl 'git clone --recurse-submodules'
abbr -a gclean 'git clean -id'
abbr -a gpristine 'git reset --hard && git clean -dfx'
abbr -a gcm 'git checkout master'
abbr -a gcd 'git checkout develop'
abbr -a gcmsg 'git commit -m'
abbr -a gco 'git checkout'
abbr -a gcount 'git shortlog -sn'
abbr -a gcp 'git cherry-pick'
abbr -a gcpa 'git cherry-pick --abort'
abbr -a gcpc 'git cherry-pick --continue'
abbr -a gcs 'git commit -S'
abbr -a gd 'git diff'
abbr -a gdca 'git diff --cached'
abbr -a gdcw 'git diff --cached --word-diff'
abbr -a gdct 'git describe --tags `git rev-list --tags --max-count=1`'
abbr -a gds 'git diff --staged'
abbr -a gdt 'git diff-tree --no-commit-id --name-only -r'
abbr -a gdw 'git diff --word-diff'
abbr -a gf 'git fetch'
abbr -a gfa 'git fetch --all --prune'
abbr -a gfo 'git fetch origin'
abbr -a gg 'git gui citool'
abbr -a gga 'git gui citool --amend'
abbr -a gignore 'git update-index --assume-unchanged'
abbr -a gignored 'git ls-files -v | grep "^[[:lower:]]"'
abbr -a git-svn-dcommit-push 'git svn dcommit && git push github master:svntrunk'
abbr -a gl 'git pull'
abbr -a glg 'git log --stat'
abbr -a glgp 'git log --stat -p'
abbr -a glgg 'git log --graph'
abbr -a glgga 'git log --graph --decorate --all'
abbr -a glgm 'git log --graph --max-count=10'
abbr -a glo 'git log --oneline --decorate'
abbr -a glol "git log --graph --pretty '%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'"
abbr -a glols "git log --graph --pretty '%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --stat"
abbr -a glod "git log --graph --pretty '%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset'"
abbr -a glods "git log --graph --pretty '%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset' --date=short"
abbr -a glola "git log --graph --pretty '%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --all"
abbr -a glog 'git log --oneline --decorate --graph'
abbr -a gloga 'git log --oneline --decorate --graph --all'
abbr -a gm 'git merge'
abbr -a gmom 'git merge origin/master'
abbr -a gmt 'git mergetool --no-prompt'
abbr -a gmtvim 'git mergetool --no-prompt --tool=vimdiff'
abbr -a gmum 'git merge upstream/master'
abbr -a gma 'git merge --abort'
abbr -a gp 'git push'
abbr -a gpd 'git push --dry-run'
abbr -a gpf 'git push --force-with-lease'
abbr -a gpf! 'git push --force'
abbr -a gpoat 'git push origin --all && git push origin --tags'
abbr -a gpu 'git push upstream'
abbr -a gpv 'git push -v'
abbr -a gr 'git remote'
abbr -a gra 'git remote add'
abbr -a grb 'git rebase'
abbr -a grba 'git rebase --abort'
abbr -a grbc 'git rebase --continue'
abbr -a grbd 'git rebase develop'
abbr -a grbi 'git rebase -i'
abbr -a grbm 'git rebase master'
abbr -a grbs 'git rebase --skip'
abbr -a grh 'git reset'
abbr -a grhh 'git reset --hard'
abbr -a grm 'git rm'
abbr -a grmc 'git rm --cached'
abbr -a grmv 'git remote rename'
abbr -a grrm 'git remote remove'
abbr -a grset 'git remote set-url'
abbr -a gru 'git reset --'
abbr -a grup 'git remote update'
abbr -a grv 'git remote -v'
abbr -a gsb 'git status -sb'
abbr -a gsd 'git svn dcommit'
abbr -a gsh 'git show'
abbr -a gsi 'git submodule init'
abbr -a gsps 'git show --pretty=short --show-signature'
abbr -a gsr 'git svn rebase'
abbr -a gss 'git status -s'
abbr -a gst 'git status'
abbr -a gstaa 'git stash apply'
abbr -a gstc 'git stash clear'
abbr -a gstd 'git stash drop'
abbr -a gstl 'git stash list'
abbr -a gstp 'git stash pop'
abbr -a gsts 'git stash show --text'
abbr -a gstall 'git stash --all'
abbr -a gsu 'git submodule update'
abbr -a gts 'git tag -s'
abbr -a gtv 'git tag | sort -V'
abbr -a gunignore 'git update-index --no-assume-unchanged'
abbr -a gunwip 'git log -n 1 | grep -q -c "\-\-wip\-\-" && git reset HEAD~1'
abbr -a gup 'git pull --rebase'
abbr -a gupv 'git pull --rebase -v'
abbr -a gupa 'git pull --rebase --autostash'
abbr -a gupav 'git pull --rebase --autostash -v'
abbr -a glum 'git pull upstream master'
abbr -a gwch 'git whatchanged -p --abbrev-commit --pretty=medium'

abbr -a npmg "npm i -g"
abbr -a npmS "npm i -S"
abbr -a npmD "npm i -D"
abbr -a npmO "npm outdated"
abbr -a npmV "npm -v"
abbr -a npmL "npm list"
abbr -a npmL0 "npm ls --depth=0"
abbr -a npmst "npm start"
abbr -a npmt "npm test"
abbr -a npmR "npm run"
abbr -a npmP "npm publish"
abbr -a npmI "npm init"

abbr -a cp "rsync -avz -hhh --progress -h"
abbr -a mv "rsync -avz -hhh --progress -h --remove-source-files"
abbr -a rsyncu "rsync -avzu -hhh --progress -h"
abbr -a rsyncsync "rsync -avzu -hhh --delete --progress -h"
